Support not changing password
bitnami/bitnami-docker-rabbitmq pull request #139
Opened 2020-11-02 16:55 UTC by msvticket

**Description of the change**

The change allows for RABBITMQ_PASSWORD to not be set and when RABBITMQ_LOAD_DEFINITIONS is set instead the rabbitmq_initialize function won't try to change the password.

**Benefits**

Together with other changes in the bitnami rabbitmq helm chart it will again be possible to load definitions.

**Possible drawbacks**

Any user password needs to be explicitly set in the definition file. If not the password will stay as it is in rabbitmq.conf, which by default is CHANGEME when using the helm chart. In the coming PR for the helm chart I will therefore expand the [documentation for loading definitions](https://github.com/bitnami/charts/tree/master/bitnami/rabbitmq#load-definitions) with the requirement to include user credentials in the definitions.  

**Applicable issues**

bitnami/charts#3675

2020-11-03 08:15 UTC, miguelaeh requested changes
Hi @msvticket ,
Thank you very much for the PR!
Looking to the changes I think it will be possible to maintain a backwards compatibilty with the logic. Could you take a look?

2020-11-03 08:15 UTC, miguelaeh commented on 3.8/debian-10/rootfs/opt/bitnami/scripts/librabbitmq.sh
> -
I think we can do here the same than in the `rabbitmq_change _password`. I mean use:
```
        if [ -z "$RABBITMQ_LOAD_DEFINITIONS" ]; then
```

instead of delete them and preserve the env var at `librabbitmq.sh`

2020-11-03 08:15 UTC, miguelaeh commented on 3.8/debian-10/rootfs/opt/bitnami/scripts/librabbitmq.sh
> +        fi
```suggestion
        if [[ -z "$RABBITMQ_LOAD_DEFINITIONS" ]]; then
            rabbitmq_change_password "$RABBITMQ_USERNAME" "$RABBITMQ_PASSWORD"
        fi
```

2020-11-03 10:45 UTC, msvticket commented
I don't see that RABBITMQ_HASHED_PASSWORD is actually used anywhere. So how about requiring only RABBITMQ_PASSWORD if RABBITMQ_LOAD_DEFINITIONS is not set?

2020-11-03 12:39 UTC, msvticket commented on 3.8/debian-10/rootfs/opt/bitnami/scripts/librabbitmq.sh
> -
I don't see that RABBITMQ_HASHED_PASSWORD is actually used anywhere. So how about requiring only RABBITMQ_PASSWORD if RABBITMQ_LOAD_DEFINITIONS is not set?

2020-11-03 12:40 UTC, msvticket commented on 3.8/debian-10/rootfs/opt/bitnami/scripts/librabbitmq.sh
> +        fi
Maybe handle $RABBITMQ_LOAD_DEFINITIONS as a boolean instead?

2020-11-04 10:04 UTC, miguelaeh requested changes

2020-11-04 10:04 UTC, miguelaeh commented on 3.8/debian-10/rootfs/opt/bitnami/scripts/librabbitmq.sh
> +export RABBITMQ_LOAD_DEFINITIONS=${RABBITMQ_LOAD_DEFINITIONS:-no}
I would set the default to yes to maintain backward compatibility

2020-11-04 10:05 UTC, miguelaeh commented
>I don't see that RABBITMQ_HASHED_PASSWORD is actually used anywhere. So how about requiring only RABBITMQ_PASSWORD if RABBITMQ_LOAD_DEFINITIONS is not set?

I agree, I can't see where is it used, and it doesn't seem to be a RabbitMQ env var neither.

2020-11-04 10:50 UTC, msvticket commented on 3.8/debian-10/rootfs/opt/bitnami/scripts/librabbitmq.sh
> +export RABBITMQ_LOAD_DEFINITIONS=${RABBITMQ_LOAD_DEFINITIONS:-no}
No. But I seem to have flipped the meaning when changing to interpreting the variable as boolean. I'll fix that.

2020-11-05 09:15 UTC, miguelaeh requested changes
Hi @msvticket ,
Thank you for the change, sorry for this I just realize the validation is missing, could you please add also a validation like:
```
    if ! is_yes_no_value "$RABBITMQ_LOAD_DEFINITIONS"; then
        print_validation_error "An invalid value was specified in the environment variable RABBITMQ_LOAD_DEFINITIONS. Valid values are: yes or no"
    fi
```

2020-11-05 10:13 UTC, msvticket commented
Done

2020-11-06 09:20 UTC, miguelaeh requested changes

2020-11-06 09:20 UTC, miguelaeh commented on README.md
> -
Please don't remove this, instead add a new section explaining the new changes

2020-11-06 10:28 UTC, msvticket commented on README.md
> -
Done

2020-11-16 09:31 UTC, merged

2020-11-16 14:36 UTC, andresbono commented
Hi @msvticket, thank you very much for implementing this fix ❤️ . Did you submit a PR for the `bitnami/rabbitmq` chart already?

2020-11-16 15:19 UTC, msvticket commented
I have a branch prepared to make a PR from. But with the changes for helm 3 I get conflicts. And I can't start using helm 3 now anyway... I have now created a PR with conflicts (bitnami/charts#4347). Maybe someone else wants to fork my repo and finish the work.