Adding script to use as k8s preStop hook
bitnami/bitnami-docker-rabbitmq pull request #142
Opened 2020-11-18 14:40 UTC by msvticket

**Description of the change**

Adding script `nodeshutdown.sh` to use as k8s preStop hook. The script will wait for the checks `check_if_node_is_mirror_sync_critical` and `check_if_node_is_quorum_critical` to become OK before proceeding to do `stop_app`.

**Benefits**

If you have a cluster with replicated queues with many messages using this script as a  this will reduce the risk for data loss especially when doing a configuration update that require all nodes/containers to be recreated.

**Possible drawbacks**

Stopping the container might take longer.

**Applicable issues**

bitnami/charts#3931

**Additional information**

2020-11-19 13:11 UTC, carrodher commented
Thanks for your contribution, is there an associated PR with the changes in the Helm Chart where the scripts are going to be used?
Just to double-check, is the default behavior of the container being modified at some point or just some scripts are going to be added to be used later on in k8s?

2020-11-19 13:17 UTC, msvticket commented
This change is only intended to be put into use by a change of a k8s manifest ie. by adding it as a preStop hook. And, yes, the idea would be to do this change in the Helm chart.

2020-11-19 13:18 UTC, msvticket commented
No PR exists yet. It wouldn't be ready before a new release of the image is made after this PR is merged.

2020-11-20 15:30 UTC, carrodher commented
Ok, understood, thanks. The changes LGTM, but I don't know if we should wait until the PR is created in the chart repository just to test them properly and see how this is going to be used.
The PR can be created anyways, we will not merge it until the changes in the image are merged and a new image version released, then we need to update the PR to use the latest image (with those changes).

2020-11-23 13:04 UTC, carrodher commented
I just set the "on-hold" label to prevent the stale bot from closing this issue

2020-12-02 09:13 UTC, msvticket commented
@carrodher How is it going with this? The corresponding PR for the helm chart was merged 6 days ago.

2020-12-02 09:28 UTC, javsalgar commented on 3.8/debian-10/rootfs/opt/bitnami/scripts/rabbitmq/nodeshutdown.sh
> +. /opt/bitnami/scripts/libhook.sh
About libhook.sh, why not including libos.sh and liblog.sh? with that we wouldn't need this new library, right?

2020-12-02 09:58 UTC, msvticket commented on 3.8/debian-10/rootfs/opt/bitnami/scripts/rabbitmq/nodeshutdown.sh
> +. /opt/bitnami/scripts/libhook.sh
No. The implementations are not the same. Read the comments.

2020-12-04 13:07 UTC, javsalgar commented
Hi,

Sorry for the delay. I've been thinking about this, and I'm starting to think that, as it is very Kubernetes specific, it would make more sense to move these scripts to the chart. We use the same scripts for other non-kubernetes platforms and they wouldn't be used. What do you think? I can create the PR in the bitnami/charts repo and let you know.

2020-12-07 15:44 UTC, msvticket commented
I don't think so. That was my original idea, but I thought it was better to put it in the image. A similar feature could very well be requested for other deployment options and having it in the image would lessen the risk for code duplication.

But most importantly I have tested the feature pretty carefully in this form and starting again with another PR would frankly be a waste of time.

2020-12-17 17:05 UTC, orirawlings commented
I was just curious about the status of this enhancement. I was hoping to update my helm release but looks like it wouldn't pick up this change even though the helm chart is otherwise ready for it.

In the meantime, is there any tagged image published with this change included I could try referencing?

2020-12-18 14:56 UTC, javsalgar requested changes
Changes requested

2020-12-18 14:56 UTC, javsalgar commented on 3.8/debian-10/rootfs/opt/bitnami/scripts/rabbitmq/nodeshutdown.sh
> +    if [ $? -eq 124]; then
Please use `[[` and add a space after  the `124`

2020-12-18 14:56 UTC, javsalgar commented on 3.8/debian-10/rootfs/opt/bitnami/scripts/rabbitmq/nodeshutdown.sh
> +    RABBITMQ_SYNC_TIMEOUT=$(($TERMINATION_GRACE_PERIOD_SECONDS - 10))
Remove the `$` before `TERMINATION`

2020-12-18 14:56 UTC, javsalgar commented on 3.8/debian-10/rootfs/opt/bitnami/scripts/rabbitmq/nodeshutdown.sh
> +	case "${flag}" in
Please add a default case to cover the invalid flags

2020-12-18 14:56 UTC, javsalgar commented on 3.8/debian-10/rootfs/opt/bitnami/scripts/rabbitmq/nodeshutdown.sh
> +if debug_execute rabbitmqctl cluster_status && [[ $RABBITMQ_SYNC_TIMEOUT > 0 ]]; then
Use `gt` instead

2020-12-18 14:56 UTC, javsalgar commented on 3.8/debian-10/rootfs/opt/bitnami/scripts/rabbitmq/nodeshutdown.sh
> +. /opt/bitnami/scripts/libhook.sh
Add

```
# shellcheck disable=SC1091
```

Do it for the rest

2020-12-18 15:01 UTC, javsalgar commented
Sorry for the delay but I was on vacation. Could you please check the requested changes? Thanks!

2020-12-31 09:59 UTC, javsalgar commented
Pinging @marcosbc as he is specialized in our bash containers.

2020-12-31 14:22 UTC, marcosbc requested changes
Thanks for the contribution! I'm adding a few comments / requests, let me know if you have any questions.

2020-12-31 14:22 UTC, marcosbc commented on 3.8/debian-10/rootfs/opt/bitnami/scripts/libhook.sh
> +}
Instead of copying / duplicating the contents of the function, I would suggest to do this:

```suggestion
#!/bin/bash
#
# Library to use for scripts expected to be used as Kubernetes lifecycle hooks

# shellcheck disable=SC1091

# Load generic libraries
. /opt/bitnami/scripts/liblog.sh
. /opt/bitnami/scripts/libos.sh

# Override functions that log to stdout/stderr of the current process, so they print to process 1
for function_to_override in stderr_print debug_execute; do
    # Output is sent to output of process 1 and thus end up in the container log
    # The hook output in general isn't saved
    eval "$(declare -f "$function_to_override") >/proc/1/fd/1 2>/proc/1/fd/2"
done
```

WDYT?

2021-01-05 21:01 UTC, cheskayang commented
thx a lot for the contribution. I'm currently having issues rolling update rabbitmq cluster,  quorum queues are experiencing message loss, hopefully, this change will solve the problem.

2021-01-07 14:20 UTC, msvticket commented on 3.8/debian-10/rootfs/opt/bitnami/scripts/rabbitmq/nodeshutdown.sh
> +	case "${flag}" in
It's indented with spaces and tabs where tabs are to be shown with the same wit as 4 spaces. But I can convert the tabs.

2021-01-07 14:21 UTC, msvticket commented on 3.8/debian-10/rootfs/opt/bitnami/scripts/libhook.sh
> +}
I don't care and think this PR should have been merged a long time ago.

2021-01-07 15:04 UTC, marcosbc approved these changes
LGTM, thanks!

2021-01-07 15:04 UTC, merged

2021-01-07 15:20 UTC, marcosbc commented
FYI we are working on releasing a new docker image with these changes. If everything goes right it will be released later today or tomorrow morning.

2021-01-07 16:40 UTC, marcosbc commented
@cheskayang Note that until the chart starts making use of the newly added scripts, you will continue finding the issues you mention. AFAIK there is no PR for the chart yet so just warning you that it may take some time.

2021-01-07 16:45 UTC, msvticket commented
The PR for the chart is actually already merged since a long time (bitnami/charts#4470). So when an image with this fixa has been built the only thing needed is to update the image tag to use in the helm chart.

2021-01-08 09:33 UTC, marcosbc commented
Hi all, RabbitMQ [`3.8.9-debian-10-r82`](https://github.com/bitnami/bitnami-docker-rabbitmq/commit/c2d40b8e587a0f98331bc250e3ca4ea8f97ce640) was released with this fix. The chart was also updated to use this Docker image in [8.6.2](https://github.com/bitnami/charts/commit/16d2aafd0776653f732f6ad9a262e6dbe6229904).