FQDN check
bitnami/bitnami-docker-rabbitmq pull request #151
Opened 2021-01-15 16:24 UTC by philippfreyer

**Description of the change**

The RabbitMQ hostname is now checked for dots (hint of it being a FQDN, which needs the variable RABBITMQ_USE_LONGNAME to be set)

**Benefits**

Less crashes on startup without explanation (previously not handled case)

**Possible drawbacks**

None to my knowledge unless non-FQDN could contain dots.

**Applicable issues**

#146 

**Additional information**

Tested it on my cluster, working there.

2021-01-18 12:51 UTC, FraPazGal requested changes
Thanks for the PR! Only a couple of comments on the README change, could you please take a look at them?

2021-01-18 12:51 UTC, FraPazGal commented on README.md
> +* `RABBITMQ_NODE_NAME`: Node name and host. E.g.: *node@hostname* or *node* (localhost won't work in cluster topology). Default **rabbit@localhost**. If using this variable, ensure that you specify a
Could we specify the required value to avoid confussion? It could be something like: "...needs to be set to `true` as well."

Also, there is a typo in the env name, it should be `RABBITMQ_USE_LONGNAME`, without the `s` at the end.

2021-01-18 14:10 UTC, philippfreyer commented on README.md
> +* `RABBITMQ_NODE_NAME`: Node name and host. E.g.: *node@hostname* or *node* (localhost won't work in cluster topology). Default **rabbit@localhost**. If using this variable, ensure that you specify a
Hi @FraPazGal
sure, I will check it again, however the environment variable needs to just be there as far as I understood the documentation, I am currently setting it to `1`. Sorry about the type, will fix it as well.

2021-01-18 14:46 UTC, FraPazGal commented on README.md
> +* `RABBITMQ_NODE_NAME`: Node name and host. E.g.: *node@hostname* or *node* (localhost won't work in cluster topology). Default **rabbit@localhost**. If using this variable, ensure that you specify a
Great! Looking at the [official documentation](https://www.rabbitmq.com/configure.html#supported-environment-variables), `RABBITMQ_USE_LONGNAME` expects the values `true/false`, though it may be accepting `1` as `true` as well. Moreover, we are setting it as `true` in our [chart](https://github.com/bitnami/charts/blob/0126ba938e019e30d103878ae7b907240af55f4a/bitnami/rabbitmq/templates/statefulset.yaml#L156), so it would be good to have the same on both places.

2021-01-18 15:25 UTC, philippfreyer commented
Added the requested fixes. Before merging, I would raise the same question that I raised in #146 again (possible inclusion of `RABBITMQ_USE_LONGNAME` in the table instead of just a description as of this PR?).

2021-01-19 11:39 UTC, FraPazGal commented
Yes, we could add it as an ENV to the list. If so, please add it to `rabbitmq-env.sh` and validate it on `librabbitmq.sh` as well.

2021-01-19 12:51 UTC, philippfreyer commented
@FraPazGal Done, done and done :-)

2021-01-20 15:52 UTC, FraPazGal reviewed
Hello @philippfreyer!

I added a few comments to have a more intuitive code, please give them a look.

2021-01-20 15:52 UTC, FraPazGal commented on 3.8/debian-10/rootfs/opt/bitnami/scripts/librabbitmq.sh
> +    check_multi_value "RABBITMQ_USE_LONGNAME" "true false"
This could actually be `check_yes_no_value "RABBITMQ_USE_LONGNAME"`, as that function checks if the values are `yes/no` or `true/false`

2021-01-20 15:52 UTC, FraPazGal commented on README.md
> +* `RABBITMQ_NODE_NAME`: Node name and host. E.g.: *node@hostname* or *node* (localhost won't work in cluster topology). Default **rabbit@localhost**. If using this variable, ensure that you specify a
It may be nitpicking, but we can now remove the part "(default is `false`)".

2021-01-20 15:52 UTC, FraPazGal commented on 3.8/debian-10/rootfs/opt/bitnami/scripts/librabbitmq.sh
> +            if [[ -z "${RABBITMQ_USE_LONGNAME:-}" ]] ; then
This `if` could now be changed to something like `if [[ "${RABBITMQ_USE_LONGNAME}" = true ]] ;`, couldn't it?

2021-01-20 15:58 UTC, philippfreyer commented on 3.8/debian-10/rootfs/opt/bitnami/scripts/librabbitmq.sh
> +    check_multi_value "RABBITMQ_USE_LONGNAME" "true false"
I had that first and then changed it since the output of `check_yes_no_value` asks for a value that is either `yes` or `no` instead of the actually required values `true` or `false`.

2021-01-20 15:59 UTC, philippfreyer commented on README.md
> +* `RABBITMQ_NODE_NAME`: Node name and host. E.g.: *node@hostname* or *node* (localhost won't work in cluster topology). Default **rabbit@localhost**. If using this variable, ensure that you specify a
Good point, will change that.

2021-01-20 16:07 UTC, philippfreyer commented on 3.8/debian-10/rootfs/opt/bitnami/scripts/librabbitmq.sh
> +            if [[ -z "${RABBITMQ_USE_LONGNAME:-}" ]] ; then
Tested it quickly, it can be changed. Will adapt.

2021-01-21 10:15 UTC, FraPazGal reviewed
These should be the last changes needed before testing this internally, please check the added comments.

2021-01-21 10:15 UTC, FraPazGal commented on 3.8/debian-10/rootfs/opt/bitnami/scripts/librabbitmq.sh
> +            if [[ "${RABBITMQ_USE_LONGNAME}" = true ]] ; then
I misinterpreted the condition and used `= true` in my example. Right now, this would actually throw an error when you are using `RABBITMQ_USE_LONGNAME` correctly. My bad! This should have been:

```suggestion
            if [[ "${RABBITMQ_USE_LONGNAME}" = false ]] ; then
```

2021-01-21 13:29 UTC, philippfreyer commented on 3.8/debian-10/rootfs/opt/bitnami/scripts/librabbitmq.sh
> +            if [[ "${RABBITMQ_USE_LONGNAME}" = true ]] ; then
And I did not catch it, thank you :-)

2021-01-21 13:38 UTC, philippfreyer commented
@FraPazGal 
I think that while it is a bit overkill for only one variable it is still worth it, considering that RabbitMQ is quite forgiving with the use of this environment variable. Adapted the code accordingly.

2021-01-21 15:15 UTC, philippfreyer commented on 3.8/debian-10/rootfs/opt/bitnami/scripts/librabbitmq.sh
> +    check_multi_value "RABBITMQ_USE_LONGNAME" "true false"
Just noticed that I commented at the wrong place:
@FraPazGal
I think that while it is a bit overkill for only one variable it is still worth it, considering that RabbitMQ is quite forgiving with the use of this environment variable. Adapted the code accordingly.

2021-01-27 13:15 UTC, FraPazGal approved these changes
LGTM! Thanks again for the PR!!

2021-01-27 13:16 UTC, merged