Moving the path for rabbitmq_combined_keys.pem due to access right is…
bitnami/bitnami-docker-rabbitmq pull request #152
Opened 2021-01-18 17:25 UTC by philippfreyer

…sues

**Description of the change**

Moving the position of `rabbitmq_combined_keys.pem` due to access right issues.

**Benefits**

The SSL code is currently not working correctly, this will help fixing it.

**Possible drawbacks**

This may affect people that mounted a preconfigured combined keys file as a workaround.

**Applicable issues**

#150

2021-01-19 08:56 UTC, dani8art requested changes
Hi @philippfreyer thanks for this PR! Please take a look at my comment

2021-01-19 08:56 UTC, dani8art commented on 3.8/debian-10/rootfs/opt/bitnami/scripts/librabbitmq.sh
> +    local -r combined_ssl_file="/opt/bitnami/rabbitmq/etc/rabbitmq/rabbitmq_combined_keys.pem"
Could we use the existing env var for `/opt/bitnami/rabbitmq/etc/rabbitmq`? `RABBITMQ_CONF_DIR` could fit this requirement, what do you think?

2021-01-19 09:04 UTC, philippfreyer commented on 3.8/debian-10/rootfs/opt/bitnami/scripts/librabbitmq.sh
> +    local -r combined_ssl_file="/opt/bitnami/rabbitmq/etc/rabbitmq/rabbitmq_combined_keys.pem"
Good point, did not notice its existence. It does definitely make sense to use it, will adapt in a second.

2021-01-19 11:13 UTC, juan131 commented on 3.8/debian-10/rootfs/opt/bitnami/scripts/librabbitmq.sh
> +    local -r combined_ssl_file="${RABBITMQ_CONF_DIR}/rabbitmq_combined_keys.pem"
Do we know the context why it was created created at `/etc` previously? Did you investigate who added this @dani8art ?
Also, It seems we're using `/opt/bitnami/rabbitmq/certs` for certificates in the chart, see: https://github.com/bitnami/charts/blob/master/bitnami/rabbitmq/templates/statefulset.yaml#L278
Shouldn't we use that directory here too?

2021-01-19 11:18 UTC, dani8art commented on 3.8/debian-10/rootfs/opt/bitnami/scripts/librabbitmq.sh
> +    local -r combined_ssl_file="${RABBITMQ_CONF_DIR}/rabbitmq_combined_keys.pem"
Regarding `/etc` it seems it we wanted to use `/tmp`, anyway, I agree with you we should use `/opt/bitnami/rabbitmq/certs` in this case we must ensure the chart is only mounting specific files inside that directory since it must be writable

2021-01-19 11:20 UTC, dani8art commented on 3.8/debian-10/rootfs/opt/bitnami/scripts/librabbitmq.sh
> +    local -r combined_ssl_file="${RABBITMQ_CONF_DIR}/rabbitmq_combined_keys.pem"
We currently cannot use this directory without change something in the chart:

```yaml
            {{- if .Values.auth.tls.enabled }}
            - name: certs
              mountPath: /opt/bitnami/rabbitmq/certs
            {{- end }}
```

2021-01-19 11:26 UTC, marcosbc commented on 3.8/debian-10/rootfs/opt/bitnami/scripts/librabbitmq.sh
> +    local -r combined_ssl_file="${RABBITMQ_CONF_DIR}/rabbitmq_combined_keys.pem"
`/etc` was a typo, initially meant to be `/tmp`, like the RabbitMQ official Docker image.

2021-01-19 12:23 UTC, philippfreyer commented on 3.8/debian-10/rootfs/opt/bitnami/scripts/librabbitmq.sh
> +    local -r combined_ssl_file="${RABBITMQ_CONF_DIR}/rabbitmq_combined_keys.pem"
How about adding an additional path variable for the combined certificate then? Any of the folders currently under discussion should not be mounted for the docker image (at least they are undocumented in `README.md`), the chart uses the certs folder for mounting the core certificates, thus it would not be writable for the combined cert (at least, to my knowledge, not in a way that kubernetes intended).
If we add an environment variable `RABBITMQ_COMBINED_CERT_PATH`, we could give it a default value (e.g. `/tmp/rabbitmq_combined_keys.pem`) that could be overwritten by anyone who wants to provide their own combined certificate file. This path could then also be checked in  https://github.com/bitnami/bitnami-docker-rabbitmq/blob/master/3.8/debian-10/rootfs/opt/bitnami/scripts/librabbitmq.sh#L411 as well, allowing (for the first time) to actually provide this combined certificate, while keeping the original logic (except for fixing the permission issue).

2021-01-19 15:34 UTC, philippfreyer commented
While testing it on my own servers, I also noticed that the way the certificates were combined was wrong. the `printf` call in XXX resulted in this output:
```
/dev/fd/63
/dev/fd/62
```

Changing the line to `cat "$RABBITMQ_SSL_CERTFILE" "$RABBITMQ_SSL_KEYFILE" > "$combined_ssl_file"` solved this issue for me.

2021-01-19 18:41 UTC, philippfreyer commented
A test with the added fixes on my servers was successful, so the changes should not have broken something. I am happy to adjust the PR still with the correct implementation regarding the discussion results (combined certificate path)

2021-01-20 09:16 UTC, dani8art commented on 3.8/debian-10/rootfs/opt/bitnami/scripts/librabbitmq.sh
> +    local -r combined_ssl_file="${RABBITMQ_CONF_DIR}/rabbitmq_combined_keys.pem"
A new env var looks good to me although we would need to adjust permission for the `/tmp` directory as well, right?  what do you think @juan131 and @marcosbc ?

2021-01-29 06:13 UTC, philippfreyer commented on 3.8/debian-10/rootfs/opt/bitnami/scripts/librabbitmq.sh
> +    local -r combined_ssl_file="${RABBITMQ_CONF_DIR}/rabbitmq_combined_keys.pem"
Any updates  @dani8art @juan131 @marcosbc ?

2021-01-29 09:35 UTC, dani8art commented on 3.8/debian-10/rootfs/opt/bitnami/scripts/librabbitmq.sh
> +    local -r combined_ssl_file="${RABBITMQ_CONF_DIR}/rabbitmq_combined_keys.pem"
Please, go ahead with the `RABBITMQ_COMBINED_CERT_PATH` suggestion

2021-01-29 16:30 UTC, philippfreyer commented on 3.8/debian-10/rootfs/opt/bitnami/scripts/librabbitmq.sh
> +    local -r combined_ssl_file="${RABBITMQ_CONF_DIR}/rabbitmq_combined_keys.pem"
Thanks, I will finish that up on monday and update the PR.

2021-02-01 06:16 UTC, philippfreyer commented on 3.8/debian-10/rootfs/opt/bitnami/scripts/librabbitmq.sh
> +    local -r combined_ssl_file="${RABBITMQ_CONF_DIR}/rabbitmq_combined_keys.pem"
@dani8art Implemented, documented, and validated the suggestion, please review again :-)

2021-02-03 11:26 UTC, dani8art approved these changes
Hi Thanks! It LGTM, My colleague @rafariossaa will integrate this into the master branch

2021-02-04 08:47 UTC, rafariossaa commented
Hi @philippfreyer , 
  I am adding this changes into our CI/CD, I will merge this PR when it is validated in our pipeline.

2021-02-04 14:12 UTC, rafariossaa requested changes

2021-02-04 14:12 UTC, rafariossaa commented on 3.8/debian-10/rootfs/opt/bitnami/scripts/librabbitmq.sh
> +    if [ ! -f "$RABBITMQ_COMBINED_CERT_PATH" ]; then
Hi,
  Just a small change here to follow our conventions. Could you change this by:
```
    if [[ ! -f "$RABBITMQ_COMBINED_CERT_PATH" ]]; then
```

2021-02-04 14:40 UTC, philippfreyer commented on 3.8/debian-10/rootfs/opt/bitnami/scripts/librabbitmq.sh
> +    if [ ! -f "$RABBITMQ_COMBINED_CERT_PATH" ]; then
Hi @rafariossaa 
sure, done :-D

2021-02-08 17:08 UTC, rafariossaa requested changes

2021-02-09 05:56 UTC, philippfreyer commented on 3.8/debian-10/rootfs/opt/bitnami/scripts/rabbitmq-env.sh
> +export RABBITMQ_COMBINED_CERT_PATH="${RABBITMQ_SSL_KEYFILE:-/tmp/rabbitmq_combined_keys.pem}"
Hi @rafariossaa
I am happy to change this in general. However, @dani8art  noticed a potential issue in the previous discussion:

> Regarding `/etc` it seems we wanted to use `/tmp`, anyway, I agree with you we should use `/opt/bitnami/rabbitmq/certs` in this case we must ensure the chart is only mounting specific files inside that directory since it must be writable

> We currently cannot use this directory without change something in the chart:

            {{- if .Values.auth.tls.enabled }}
            - name: certs
              mountPath: /opt/bitnami/rabbitmq/certs
            {{- end }}

Is this issue taken care of? I would also add that the path is also problematic if the user creates his own deployment / statefulset based on the Bitnami RabbitMQ images and does not know about any restrictions regarding mounting only single files.

I will wait for your answer before changing anything. If this issue is taken care of, then I will happily change the base folder.

2021-02-10 12:51 UTC, rafariossaa approved these changes
LGTM

2021-02-10 12:51 UTC, rafariossaa commented on 3.8/debian-10/rootfs/opt/bitnami/scripts/rabbitmq-env.sh
> +export RABBITMQ_COMBINED_CERT_PATH="${RABBITMQ_SSL_KEYFILE:-/tmp/rabbitmq_combined_keys.pem}"
Yes, I overlooked that part.
LGTM.

2021-02-10 12:51 UTC, merged