follow symlinks when checking whether a directory is empty or not
bitnami/bitnami-docker-rabbitmq pull request #184
Opened 2021-11-24 11:35 UTC by elchenberg

**Description of the change**

Shell functions follow symlinks when they check whether a directory is empty or not.

**Benefits**

Persisted data will be detected. The `$RABBITMQ_DATA_DIR` has been replaced with a symlink to /var/lib/rabbitmq/mnesia
but the function that is used by librabbitmq.sh to detect persisted data (`is_mounted_dir_empty`)
did not follow symlinks so it did not detect persisted data anymore.

**Possible drawbacks**

**Applicable issues**

**Additional information**

2021-11-24 15:49 UTC, elchenberg commented
More context and steps to reproduce:

I am using the bitnami/rabbitmq chart and tried to update it from v8.24.2 to v8.24.3.

Version 8.24.2 uses the image docker.io/bitnami/rabbitmq:3.9.8-debian-10-r6 and version 8.24.3 uses docker.io/bitnami/rabbitmq:3.9.9-debian-10-r0.

Steps to reproduce:

```sh
# Install version 8.24.2 of the chart
helm install rabbitmq bitnami/rabbitmq --set persistence.enabled=true --version 8.24.2 --kube-context kind-kind --namespace rabbitmq --create-namespace --wait
# Restart the pod
kubectl --context kind-kind --namespace rabbitmq delete pod/rabbitmq-0
# Inspect the log output. The last line should contain 'Persisted data detected. Restoring...'.
kubectl --context kind-kind --namespace rabbitmq logs pod/rabbitmq-0 | head -n9

# Clean up the namespace
kubectl --context kind-kind delete namespace rabbitmq --ignore-not-found

# Install version 8.24.3 of the chart
helm install rabbitmq bitnami/rabbitmq --set persistence.enabled=true --version 8.24.3 --kube-context kind-kind --namespace rabbitmq --create-namespace --wait
# Restart the pod
kubectl --context kind-kind --namespace rabbitmq delete pod/rabbitmq-0
# Inspect the log output. There is no 'Persisted data detected. Restoring...'.
kubectl --context kind-kind --namespace rabbitmq logs pod/rabbitmq-0 | head -n9
```

This indicated to me that this line in the librabbitmq.sh script does not work as expected: https://github.com/bitnami/bitnami-docker-rabbitmq/blob/31f5848743537823b208603d4eb2c14081147447/3.9/debian-10/rootfs/opt/bitnami/scripts/librabbitmq.sh#L741

The data seems to be persisted and restored nevertheless (somehow) but the password gets rehashed needlessly.

2021-11-25 09:20 UTC, Mauraza commented
Hi @elchenberg,

Thanks for the PR!. I'm going to do some tests and we will update the thread when we have more information.

2021-12-13 10:44 UTC, elchenberg commented
Any updates, @Mauraza? :slightly_smiling_face:

2021-12-14 11:39 UTC, Mauraza commented
Sorry I was on PTO. I'm testing the changes, I will update the thread with more information.

2022-02-01 10:05 UTC, migruiz4 commented
Hi @elchenberg,

I'm sorry for the late response. I will take care of testing and reviewing this PR. 
The changes look good to me, but I would like to verify that RabbitMQ works fine with these changes.

2022-02-23 14:57 UTC, Becram commented
@elchenberg @migruiz4  I have similar issue this might fix too

2022-02-24 14:49 UTC, migruiz4 commented
I'm sorry again for the late response, but this change is being delayed since it modifies the functions `is_mounted_dir_empty` and `is_dir_empty` inside `libos.sh`.

Although the change may look harmless, these two functions are used almost in every single one of our images and it is hard to measure its real impact.

In addition, we haven't received feedback about similar issues in any other asset, so it is apparently only affecting RabbitMQ.

I would appreciate it if we could change the scope of this change, and instead apply a fix at `librabbitmq.sh` where these functions are used. And if similar issues are reported in other assets then apply the change to `libos.sh`.

2022-02-28 08:51 UTC, elchenberg commented
@migruiz4 I understand. PR #194 has been merged and my issue is resolved.

2022-03-01 09:41 UTC, fmulero commented
Thanks a lot @elchenberg for letting us know it and so sorry about the delay.

2022-03-01 10:22 UTC, elchenberg commented
@fmulero No worries! Thank you for taking care and for being cautious with potentially breaking changes. :slightly_smiling_face:

2022-03-01 12:34 UTC, marcosbc commented
Hi, unfortunately we have needed to revert #194, as it was affecting (and breaking) other apps as was mentioned earlier by @migruiz4.

We would recommend to instead update this specific line, so it calls "is_mounted_dir_empty" to the realpath of the directory, but only inside [`librabbitmq.sh`](https://github.com/bitnami/bitnami-docker-rabbitmq/blob/master/3.9/debian-10/rootfs/opt/bitnami/scripts/librabbitmq.sh).

2022-03-17 13:59 UTC, elchenberg commented
I reverted my first commit and used realpath only to check for persisted data. I don't know if this works for #194, but it fixes my issue.

2022-03-21 14:42 UTC, marcosbc reviewed
Thanks for making this change! Just a small request, but apart from that it looks good to me.

2022-03-21 14:42 UTC, marcosbc commented on 3.9/debian-10/rootfs/opt/bitnami/scripts/librabbitmq.sh
> +    # use realpath to avoid symlink issues
Could you add some more info like the issue ID to the comment? e.g.:
```suggestion
    # use realpath to avoid symlink issues (#184)
```

2022-03-21 14:43 UTC, migruiz4 requested changes
Thank you @elchenberg for applying the suggested change.

Your PR looks good to me, but it would be nice if you could reference this PR in the comment.

2022-03-21 14:43 UTC, migruiz4 commented on 3.9/debian-10/rootfs/opt/bitnami/scripts/librabbitmq.sh
> +    # use realpath to avoid symlink issues
Could you please reference this PR in the comment? This way others will know why this was needed.
```suggestion
    # Use realpath to avoid symlink issues
    # ref: https://github.com/bitnami/bitnami-docker-rabbitmq/pull/184
```

2022-03-22 08:01 UTC, elchenberg commented on 3.9/debian-10/rootfs/opt/bitnami/scripts/librabbitmq.sh
> +    # use realpath to avoid symlink issues
Thanks, I applied your suggestion.

2022-03-22 13:01 UTC, merged